### ISSUE TITLE
Allow for PIV cards to be FIDO2 Authenticators

### ISSUE THREAD

**Issue by adricasti** [usnistgov/FIPS201#224]
**Organization Name**: HID Global

**Organization Type**: 2-Industry
 
**Reference**: Section 4.2 PIV Card Logical Characteristics
 
**Comment (Include rationale for comment)**: Add the ability for a PIV card to optionally support the FIDO2 protocol, that is widely supported by the industry. This would have benefits including:
- Such FIDO enabled PIV card would natively work with many applications that don’t support PIV today; for example, a PIV cardholder could use the FIDO capability on his PIV card to authenticate to a cloud application on his phone using the NFC antenna embedded in the phone without using a derived credential (while still leveraging the FIPS 140 certification of the PIV card for protection of the crypto materials). 
- The PIV issuance system could configure the FIDO assertion certificate on the PIV card using the PIV digital signatory so that an Identity Provider could be configured to only accept FIDO credentials issued by the agency or the US Federal government at large. 
- It would be possible for the PIV PIN and FIDO PIN to be one and the same inside the PIV card so that there is no new PIN management to add for the FIDO part. 
 
**Suggested Change**: Add to the fourth paragraph that states "This Standard also defines optional data elements for the PIV Card data model. These optional data elements include" a bullet saying:
- A FIDO2 compliant credential including asymmetric keys, attestation and other data required for FIDO2 compliance

**Comment by jimfenton** [comment]
Recommend not accepting:

* While we contemplate FIDO authenticators being suitable Derived PIV credentials, if the PIV card itself is available, its native PIV capability should be used when possible rather than a derived PIV.
* When authenticating to a non-PIV relying party, the PIV card should not be used.
* The form factor of PIV cards is incompatible with most FIDO authenticators (except for possible use of NFC) unless an adapter is used.
* Provision would need to be made on the PIV card design for FIDO features such as the activation button when used.

**Comment by regenscheid** [comment]
Agree- not accept.  The PIV specifications do not currently prohibit the inclusion of other functionality, like a FIDO applet, on a card.  The topic of other authenticators will be covered by a revision to SP 800-157.
