### ISSUE TITLE
If present, the cryptographic operations that use the PIV secure messaging key SHALL..

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#318]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self 
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.7 Line 1905-1907
 
**Comment (Include rationale for comment)**: "The cryptographic operations that use the PIV secure messaging key SHALL be available through the contact and contactless interfaces of the PIV Card."

 
**Suggested Change**: Replace with "If present, the cryptographic operations that use the PIV secure messaging key SHALL be available through the contact, virtual contact, and contactless interfaces of the PIV Card."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Recommend Accept

**Comment by regenscheid** [comment]
The existing text is potentially confusing, possibly suggesting both the contact and virtual contact interfaces must be used. We will revise the text in the final version.

**Comment by hferraio** [comment]
I think making changes is confusing. The text we have is appropriate and I suggest to leave it  "as is"

 The secure messaging key IS the VCI for the most part, so it is a bit weird to say  it is used WITH VCI? The secure messaging key is also used to establish a plain secure channel (no VCI) in order to do OCC-AUTH.  

We might want to point to [SP 800-73 ](https://csrc.nist.gov/publications/detail/sp/800-73/4/final )table 4b where use of key is very clearly specified.

**Comment by regenscheid** [comment]
As described above, there are no situations where the secure messaging keys themselves would be used over VCI (as opposed to being used over the contactless interface to establish the VCI).  Therefore, the existing text is appropriate.

**Comment by jglosx3** [comment]
Declined:  there are no situations where the secure messaging keys themselves would be used over VCI (as opposed to being used over the contactless interface to establish the VCI).  Therefore, the existing text is appropriate.
