### ISSUE TITLE
Duplicate sentence

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#393]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 902-903
 
**Comment (Include rationale for comment)**: "The cardholder may also apply for reissuance of a PIV Card if one or more logical credentials have been compromised."
 
**Suggested Change**: The prior sentence states "...a PIV Card that has been compromised…".  This includes compromise of a "logical credential" such as the PIN that activates a PIV-AUTH credential.  This sentence is a duplicate.  Recommend deleting it.  Any compromise forces re-issuance.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to keep both sentences since the the first (prior) sentence is about printed attributes on the card causing an reissuance. The following sentence is about the digital data  stored on card that cause a reissuance. -- all other cases is post-issuance update (not reissuance).  Suggest to remove "compromised" from the prior sentence as it is represented in the following sentence.

**Comment by regenscheid** [comment]
Decline. We want to be explicit that you may reissue the card if the logical credentials have been compromised.  We think it is clearer to keep both, although we acknowledge the point the commenter made.
