### ISSUE TITLE
Need positive affirmation of the receipt of the issued derived PIV credential.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#408]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1108-1110
 
**Comment (Include rationale for comment)**: "The issuer SHALL attempt to promptly notify the cardholder of the binding of a derived PIV credential through an independent means that would not afford an attacker an opportunity to erase the notification."
 
**Suggested Change**: It is not clear what risk is being mitigated by this statement.

The focus of the sentence is notification of binding, yet the binding happens with positive participation of the recipient by using their PIV card.

It may be that "…the binding of a derived PIV credential…" is actually ""binding and issuance"".  In that context, positive affirmation of the receipt of the issued derived PIV credential is important.

Clarify.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
More typically, a derived PIV credential will be bound to the PIV account after issuance, if there is an issuance (as opposed to placement of a certificate on a mobile device, or use of a physical authenticator as a derived PIV credential). The requirement for notification is a mitigation against mis-authentication of the subscriber, since binding of a new DPC is somewhat more significant than an individual authentication event. It is also included to be consistent with the recommendation in SP 800-63B section 6.1.2.1.

Recommend "noted".

**Comment by jimfenton** [comment]
The extra round-trip of providing a positive conformation doesn't add substantially to security and interferes with usability. Not accepted.

**Comment by jglosx3** [comment]
Declined- The extra round-trip of providing a positive conformation doesn't add substantially to security and interferes with usability.
