### ISSUE TITLE
Missing OCC option.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#471]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2207
 
**Comment (Include rationale for comment)**: "...for presentation of the PIN and acquisition of a biometric sample"

Missing OCC option.

**Suggested Change**: Recommend being explicit if OCC is not valid to activate the card in this scenario.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
suggest to accept to clarify.  On-card comparison biometric data should never be used to release off-card comparison biometric.  It would introduce an attack vector (see #582).  Also, if it would be possible to activate PIN protected  BIO-A with OCC, rather than PIN, it would result in two of the same factor (something you are twice) rather than 2FA.  It would stay a 1 factor.

**Comment by regenscheid** [comment]
We would not expect OCC to be used to unlock a card to release a biometric template, but there doesn't seem to be a compelling reason to prohibit this (as that might require additional logic on the card).
