### ISSUE TITLE
Expiration dates: Which are for the card? Which for the authentication mechanism?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#476]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2323-2325
 
**Comment (Include rationale for comment)**: This requirement highlights that there are too many expiration dates on the card.  Which are for the card? Which for the authentication mechanism?

**Suggested Change**: Sym-CAK is deprecated, yet this comment still applies to other authentication methods.

Certificates do not inform if a card is expired.  That information is only in the CHUID expiration date field.  This should not be used/recommended by this standard.

Certificates shall expire on or before the card.  These are the expiration dates critical to the operation of an access control system. 

The CHUID and card expiration should not be referenced here, nor in all PKI driven authentication methods supported by the PIV card.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to use same text as in line 2214 - 2215 (not 2216) for clarity.  

Note: Different expiration dates are necessary between card and certificate - since agencies/department want 6 year cards and be able to re-key  PKI keys and certificate once.  An unexpired certificate is therefore proof that card has not expired ( since certs are required to have an expiration within the 6 years.)

**Comment by jimfenton** [comment]
Noted. Certificates are already required to expire no later than the card.

**Comment by regenscheid** [comment]
Will clarify- replace the first bullet in Section 6.2.4 with the first bullet in Section 6.2.1.1, saying:
The CHUID or another data element is read from the card. The signature of the
CHUID or another data element is verified to ensure that the card has not expired
and that the card comes from a trusted source.

With the footnote: The PIV authentication certificate or card authentication certificate may be leveraged instead of the CHUID to verify that the card is not expired.
