### ISSUE TITLE
Remove "SHALL be monitored by staff at the station location while  it is being used."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#580]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 796
 
**Comment (Include rationale for comment)**: This process as whole needs to better defined with controls and compensating measure. Can envision, permanent locations, mobile enrollment container, and packable suitcase type of enrollments. Recommend that physical security controls like sensors that count people into a area, cameras their views, recording resolution and frame rate of the enrollment be defined as controls. Software self check, terminal vs workstation and hardware tampering devices would be additional controls. The controls would define how the process has to be monitored. Recommend these be addressed in SP 800-63 series of publications.
 
**Suggested Change**: Remove "SHALL be monitored by staff at the station location while it is being used." Suggest this be addressed in SP 800-63 series of documents.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
This issue is the representative issue for comments received on the subject of SRIP's requirement for a local staff to monitor station while it is being used.  These comments are in issue  [213](https://github.com/usnistgov/FIPS201/issues/213), [554](https://github.com/usnistgov/FIPS201/issues/554), [273](https://github.com/usnistgov/FIPS201/issues/273), [552](https://github.com/usnistgov/FIPS201/issues/552), [271](https://github.com/usnistgov/FIPS201/issues/271), [379](https://github.com/usnistgov/FIPS201/issues/379) and [377](https://github.com/usnistgov/FIPS201/issues/377) and suggest:

- to remove entire 4th paragraph (line 795-812) and footnote 9 and instead point to SP 800-63A  (STA [554](https://github.com/usnistgov/FIPS201/issues/554)  and duplicate [273](https://github.com/usnistgov/FIPS201/issues/273))
- to remove 1st bullet (lines 796-797) and instead pointing to SP 800-65A 
- remove phrase "monitored by staff" 

Arguments for removal include:
-process as whole needs to better defined in SP 800-63A with controls and compensating measure. Can envision, permanent locations, mobile enrollment container, and packable suitcase type of enrollments. Suggest that the process only needs to be monitored and SP 800-63 should be the place to define controls rather than FIPS 201-3.
- test in FIPS 201-3 is superseded by NIST SP 800-63A 5.3.3.2 describing attributes exceeding the confidence and security attained by local operators/staff. 
- DHS want us to further define “monitored by staff” so that video monitoring from a local station is possible.  DHS are concerned that kiosks in hallways or airport environment are unlikely to have staff.  - at the same time DHS also says: 
- that adding staff does not add security and that 800-63A already requires tamper resistance and scene camera. Further detail of ‘controlled area could go in SP 800-79 also.

**Comment by regenscheid** [comment]
Decline. This issue was discussed at length during the development of the the FIPS 201-3 draft.  Supervised remote identity proofing stations need to be in staffed locations to protect against equipment tampering.  This could be revisited in the next revision of FIPS 201.  The update to SP 800-79 will provide additional clarifications regarding the responsibilities of the on-site monitoring staff.
