### ISSUE TITLE
Explicitly recognize state issued mobile Driver's Licenses

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#594]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7 Line 731
 
**Comment (Include rationale for comment)**: Correcting phraseology and explicitly recognizing state issued mobile Drive's Licenses and State and jurisdictionally issued identity cards and mobile identity credentials (such as DC and US Territories) issued in accordance with Read ID requirements  as valid ID for enrollment for PIV.
 
**Suggested Change**: driver's license, mobile driver’s license, or state or jurisdictionally identity credentials issued in compliance with Real-ID requirements. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
This issue represents a collection of issues about the inclusion of 'mobile driver's licenses' as primary  id source document (line 731) and as secondary id source document (line 739)  .  It represents issue [577](https://github.com/usnistgov/FIPS201/issues/577) asking for primary source document and  issue [578](https://github.com/usnistgov/FIPS201/issues/578) asking for 2ndary source document. 


Note:  The issue about explicitly recognizing State and jurisdictionally issued IDs is represented in issue [376](https://github.com/usnistgov/FIPS201/issues/376). So, this issue here can be closed.

**Comment by regenscheid** [comment]
Decline, per above.  Note that if mobile drivers license become recognized as equivalent to physical Real-ID-compliant drivers licenses then they would be covered by the existing text.

**Comment by jglosx3** [comment]
Decline: The text has been updated with a reference to applicable DHS enforcement requirements for REAL_ID compliance credentials.
