### ISSUE TITLE
10 consecutive PIN retries

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#597]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 993 and 2006
 
**Comment (Include rationale for comment)**: In lines 993 and 2006, it says that a maximum of 10 consecutive PIN retries may be permitted before a card is locked, unless the individual government agency requires a smaller cap. The number 10 seems excessive here. For most applications (credit card, bank account, email accounts), three is the maximum number. Unless there is a
compelling reason to allow 10 tries, at most we suggest 5. 

**Suggested Change**: N/A
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend not accepting. Note that FIPS 201-2 did not specify an overall maximum at all, leaving the decision up to individual agencies.

The main purpose of the limit on PIN retries is to address potential brute-force (guessing) attacks on the PIN. These attacks are more difficult with the PIV than with credit cards, etc. because PIV uses at least a 6-digit PIN while the other examples generally only require 4 digits. This makes allowing 10 retries reasonable. Note that individual agencies still have the flexibility to set a lower limit.

**Comment by regenscheid** [comment]
Decline- There does not seem to be a compelling reason to choose 5 over 10.
