### ISSUE TITLE
OCC needs retry limit

### ISSUE THREAD

**Issue by jimfenton** [usnistgov/FIPS201#615]
Per SP 800-63B Section 5.2.3, rate limiting needs to be used for verification of a biometric. Since PIV cards do not have a time reference and no PAD, OCC would need to use a hard limit of 5 consecutive failures (note: this limit is likely to change in SP 800-63B-4).

Although PIV cards apparently have provision to limit the number of OCC retries, this limit does not seem to be specified anywhere, and should be. Also, the language about PIV card activation reset in section 2.9.3 should also refer to procedures for resetting the OCC failure counter.

**Comment by gfiumara** [comment]
[800-73-4](https://doi.org/10.6028/NIST.SP.800-73-4) section 3.2.2 (page 15) says: 
 > The initial value of the retry counter...**[is] issuer dependent**.

The value must be <= 15, based on the way the card APDUs are returned.

**Comment by gfiumara** [comment]
I think reset procedures for OCC are handled on the paragraph starting on line 1049. This implies that a cardholder cannot use the many methods they have available to reset PIN to also reset OCC. I am assuming this is partially because the OCC data stored on the card is not required to be in a standard format, and so use of the card manufacturer's software may be required to make new OCC templates.

Line 1051 states that a biometric comparison must be made to the PIV enrollment record. If OCC doesn't work because you have developed a scar, it's highly likely that comparison will also fail to the enrollment record. We should clarify the fallback here.

This document also doesn't specify if only one of the two OCC fingers can be replaced and/or if they can be replaced with a different finger position. The former seems like it would be implementation-specific, based on how the card manufacturer stores their data. The latter is dependent on how the card would read/write the BIT group template. This may well be a separate issue.

**Comment by gfiumara** [comment]
We noted that the failure counter can't be reset. Only new fingerprints put on the card.
